Repository debatecore/tau, pull requests merged in 2024-12, with the labels that each got.

#27 [26] Don't require a .env file to function
  src/setup.rs
Labels: enhancement

#29 [28] Dockerize better
  .dockerignore
  Dockerfile
  README.md
  build.rs
  compose.yaml
  dbinit-dev.sh
  dbinit.sh
Labels: enhancement

#31 [22] Start sql migrations (implement creation of tables)
  build.rs
  migrations/20241219_init.sql
  src/database/mod.rs
  src/main.rs
  src/setup.rs
Labels: enhancement

#36 [35] fix migrations order
  migrations/20241219_init.sql
Labels: bug

#34 [32] unify database url env variable naming
  README.md
  src/database/mod.rs
Labels: enhancement

#39 [37] swap ULID for UUIDv7
  Cargo.lock
  Cargo.toml
  src/users/mod.rs
Labels: enhancement, dependencies

#40 [30] report git head match state in /version-details
  build.rs
  src/routes/version.rs
Labels: enhancement

#43 [42] debate-teams helper, sessions table, more
  migrations/20241219_init.sql
Labels: enhancement
